# Generated by Django 6.0.8 on 2026-08-10 07:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='drink',
            name='brand',
            field=models.CharField(choices=[('starbucks', '스타벅스'), ('ediya', '이디야커피'), ('mega', '메가MGC커피'), ('compose', '컴포즈커피'), ('gongcha', '공차'), ('baikdabang', '빽다방'), ('mammoth', '매머드커피'), ('monster', '몬스터'), ('hotsix', '핫식스'), ('redbull', '레드불'), ('pepsi', '펩시'), ('cocacola', '코카콜라'), ('custom', '직접 입력')], default='custom', max_length=20),
        ),
        migrations.AlterField(
            model_name='drink',
            name='caffeine_mg',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='drink',
            name='type',
            field=models.CharField(choices=[('coffee', '커피'), ('tea', '차'), ('soda', '탄산'), ('energy', '에너지드링크'), ('other', '기타')], default='coffee', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='drink',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'brand', 'name', 'size'), name='uniq_active_drink_per_user'),
        ),
    ]
