# Generated by Django 6.0.8 on 2026-08-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_drink_is_active_alter_drink_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='brand',
            field=models.CharField(choices=[('starbucks', '스타벅스'), ('compose', '컴포즈커피'), ('baik', '빽다방'), ('mammoth', '매머드커피'), ('ediya', '이디야커피'), ('mega', '메가엠지씨커피'), ('gongcha', '공차'), ('custom', '직접 입력')], default='custom', max_length=20),
        ),
        migrations.AlterField(
            model_name='drink',
            name='type',
            field=models.CharField(choices=[('coffee', '커피'), ('tea', '차'), ('energy', '에너지드링크'), ('soda', '탄산'), ('other', '기타')], default='coffee', max_length=20),
        ),
    ]
