# Generated by Django 6.0.8 on 2026-08-13 07:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_alter_drink_brand'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='drink',
            name='uniq_active_drink_per_user',
        ),
        migrations.AddField(
            model_name='drink',
            name='custom_brand_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name='drink',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'brand', 'custom_brand_name', 'name', 'size'), name='uniq_active_drink_per_user'),
        ),
    ]
