# Generated by Django 6.0.8 on 2026-08-14 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_remove_drink_uniq_active_drink_per_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caffeinelog',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
