# Generated by Django 6.0.8 on 2026-08-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_caffeinelog_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleeplog',
            name='residual_mg_at_sleep',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
