# Generated by Django 6.0.8 on 2026-08-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_sleeplog_residual_mg_at_sleep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='brand',
            field=models.CharField(choices=[('starbucks', '스타벅스'), ('compose', '컴포즈커피'), ('baik', '빽다방'), ('mammoth', '매머드커피'), ('ediya', '이디야커피'), ('mega', '메가엠지씨커피'), ('gongcha', '공차'), ('pepsi', '펩시'), ('cocacola', '코카콜라'), ('energy', '에너지드링크'), ('custom', '직접 입력')], default='custom', max_length=20),
        ),
    ]
