# Generated by Django 6.0.8 on 2026-08-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_alter_drink_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='icon_key',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
