# Generated by Django 6.0.8 on 2026-08-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allnight', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allnightsession',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='allnightsession',
            name='status',
            field=models.CharField(choices=[('active', '진행중'), ('completed', '종료'), ('aborted', '중단')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='allnightsession',
            name='target_time',
            field=models.DateTimeField(),
        ),
    ]
