"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


def _env(key, default=None):
    # 환경변수가 없거나 빈 문자열이면 default. (.env에 KEY= 로만 남은 경우 대응)
    val = os.environ.get(key)
    return val if val not in (None, "") else default


def _env_bool(key, default):
    return str(_env(key, default)).strip().lower() in ("1", "true", "yes", "on")


def _env_list(key, default):
    # 쉼표로 구분된 환경변수를 리스트로. 빈 값은 걸러낸다.
    return [item.strip() for item in _env(key, default).split(",") if item.strip()]


# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 운영에서는 .env의 DJANGO_SECRET_KEY로 반드시 덮어쓴다. 아래 값은 로컬 개발 폴백.
SECRET_KEY = _env(
    "DJANGO_SECRET_KEY",
    'django-insecure-ydmu6++nun6$ub$(y^sm=q&e1@(tcgn^z(xzkpa_ppw50)i4#c',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool("DJANGO_DEBUG", True)

ALLOWED_HOSTS = _env_list("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1")

CSRF_TRUSTED_ORIGINS = _env_list("CSRF_TRUSTED_ORIGINS", "http://localhost:8000")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'accounts',
    'allnight',
    'diary',
    
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.kakao',
]

SITE_ID = 1

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "EXCEPTION_HANDLER": "config.exception_handlers.custom_exception_handler",
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    #kakao
    'allauth.account.middleware.AccountMiddleware',
]
#소셜로그인 동작설정
SOCIALACCOUNT_LOGIN_ON_GET = False # 폼 + CSRF방어
SOCIALACCOUNT_EMAIL_REQUIRED = False # 카카오가 이메일 안줘도 가입가능
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none' # 소셜가입시 이메일 인증절차 생략
SOCIALACCOUNT_EMAIL_AUTHENTICATION = False # 자동연결차단
LOGIN_REDIRECT_URL = "/" # 로그인 후 리다이렉트 주소 (ACCOUNT_ADAPTER가 없는 예외 상황용 폴백)
ACCOUNT_ADAPTER = "accounts.adapters.AccountAdapter"
SOCIALACCOUNT_ADAPTER = "accounts.adapters.KakaoSocialAccountAdapter"
ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',


        'DIRS': [BASE_DIR / 'templates'], # templates 디렉토리 참조하도록

        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# DB_ENGINE 미설정 시 로컬 개발용 SQLite로 폴백. 운영에서는 .env에
# DB_ENGINE=django.db.backends.mysql (드라이버: mysqlclient) 및 접속 정보를 채워 전환한다.

DB_ENGINE = _env("DB_ENGINE", "django.db.backends.sqlite3")

if DB_ENGINE == "django.db.backends.sqlite3":
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': DB_ENGINE,
            'NAME': os.environ.get("DB_NAME", ""),
            'USER': os.environ.get("DB_USER", ""),
            'PASSWORD': os.environ.get("DB_PASSWORD", ""),
            'HOST': os.environ.get("DB_HOST", "127.0.0.1"),
            'PORT': os.environ.get("DB_PORT", "3306"),
            'OPTIONS': {'charset': 'utf8mb4'},
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = _env("TIME_ZONE", "Asia/Seoul")

USE_I18N = True

USE_TZ = True


# 세션 / 보안 쿠키
# HTTPS 배포 환경에서는 .env에서 SESSION_COOKIE_SECURE/CSRF_COOKIE_SECURE를 True로 설정.
SESSION_COOKIE_SECURE = _env_bool("SESSION_COOKIE_SECURE", False)
CSRF_COOKIE_SECURE = _env_bool("CSRF_COOKIE_SECURE", False)
SESSION_COOKIE_AGE = int(os.environ.get("SESSION_COOKIE_AGE", "1800"))

# HTTPS 하드닝 — 개발 기본값은 모두 off. 운영(nginx+SSL) .env에서 켠다.
SECURE_SSL_REDIRECT = _env_bool("SECURE_SSL_REDIRECT", False)
SECURE_HSTS_SECONDS = int(os.environ.get("SECURE_HSTS_SECONDS", "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", False)
SECURE_HSTS_PRELOAD = _env_bool("SECURE_HSTS_PRELOAD", False)
# nginx가 X-Forwarded-Proto 헤더로 원 요청 스킴을 전달하는 경우 True.
if _env_bool("USE_X_FORWARDED_PROTO", False):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

SOCIALACCOUNT_PROVIDERS = {
    "kakao": {
        "APP": {
            "client_id": os.environ.get("KAKAO_REST_API_KEY"), # .env에서 읽어온 REST API 키
            "secret": os.environ.get("KAKAO_CLIENT_SECRET"),   # .env에서 읽어온 Client Secret
            "key": "",
        }
    }
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [BASE_DIR / 'static']

# collectstatic 수집 위치. 운영에서 nginx가 이 디렉토리를 정적 파일로 서빙한다.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# 운영(DEBUG=False)에서는 파일명에 콘텐츠 해시를 붙여(예: base.a1b2c3.css) 배포마다
# URL이 바뀌게 한다. nginx의 30일 캐시(expires 30d)와 맞물려도 재배포 시 즉시 반영되어
# 강력 새로고침 없이 최신 정적 파일을 받게 된다. 로컬 개발은 collectstatic을 매번
# 돌리지 않으므로 manifest 오류를 피하기 위해 기본 스토리지를 유지한다.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": (
            "django.contrib.staticfiles.storage.ManifestStaticFilesStorage"
            if not DEBUG
            else "django.contrib.staticfiles.storage.StaticFilesStorage"
        ),
    },
}

